### ISSUE TITLE
Refactor getUnprocessed to use DynamoDB scan

### ISSUE THREAD

**Issue by alexanderdean** [snowplow-archive/snowplow-snowflake-loader#17]
If DynamoDB read throughput is too low (and intermittently even when it's not), it's quite easy to see the Spark job failing 2 minutes in with:

```
17/09/30 14:46:07 ERROR ApplicationMaster: User class threw exception: shadeaws.AbortedException: 
shadeaws.AbortedException: 
	at shadeaws.internal.SdkFilterInputStream.abortIfNeeded(SdkFilterInputStream.java:51)
	at shadeaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:71)
	at shadeaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:489)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:126)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:215)
	at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1240)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:802)
	at shadeaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:109)
	at shadeaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:43)
	at shadeaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:70)
	at shadeaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1503)
	at shadeaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1226)
	at shadeaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
	at shadeaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at shadeaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at shadeaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at shadeaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at shadeaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at shadeaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at shadeaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2089)
	at shadeaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2065)
	at shadeaws.services.dynamodbv2.AmazonDynamoDBClient.executeGetItem(AmazonDynamoDBClient.java:1173)
	at shadeaws.services.dynamodbv2.AmazonDynamoDBClient.getItem(AmazonDynamoDBClient.java:1149)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.RunManifests$.isInManifests(RunManifests.scala:179)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.RunManifests.contains(RunManifests.scala:50)
	at com.snowplowanalytics.snowflake.core.ProcessManifest$$anonfun$getUnprocessed$1.apply(ProcessManifest.scala:44)
	at com.snowplowanalytics.snowflake.core.ProcessManifest$$anonfun$getUnprocessed$1.apply(ProcessManifest.scala:44)
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike$class.filterNot(TraversableLike.scala:267)
	at scala.collection.AbstractTraversable.filterNot(Traversable.scala:104)
	at com.snowplowanalytics.snowflake.core.ProcessManifest$.getUnprocessed(ProcessManifest.scala:44)
	at com.snowplowanalytics.snowflake.transformer.Main$.main(Main.scala:19)
	at com.snowplowanalytics.snowflake.transformer.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:637)
```

This only occurs on pipelines which have frequent runs / a long history of runs (because more archived folders in S3 to reconcile with manifest).

**Comment by chuwy** [comment]
Hm. How often does it happen? We can refactor manifests to use single scan to get all run ids rather than checking each folder against DynamoDB table.

**Comment by alexanderdean** [comment]
Yes, it feels like there is something very inefficient about the way the manifest is interacted with... I'm rerunning the pipeline to see if the problem is intermittent.

**Comment by chuwy** [comment]
After closer look it doesn't seem throughput exception for me - there's specific exception type for that.

**Comment by alexanderdean** [comment]
Right - something else, and unfortunately intermittent (the rerun just went through fine, nothing changed in-between runs).

**Comment by alexanderdean** [comment]
It's failing about half the time.

**Comment by alexanderdean** [comment]
Actually now it's failing consistently for a given user.

**Comment by alexanderdean** [comment]
Bringing forwards as this is a showstopper for the release.

**Comment by chuwy** [comment]
Ok, requested an access to investigate.

**Comment by alexanderdean** [comment]
If this helps - super weird but it feels like the problem manifests if the loader is run too soon after the last run. No idea how this could trigger this.

**Comment by chuwy** [comment]
What I've learned so far is that something tries to interrupt a main driver's thread with AWS SDK checks. And SDK silently swallows this `InterruptedException`and turns it into a `AbortedException`. Presumably this *something* is inside spark, because nothing else assumes parallel threads.

**Comment by chuwy** [comment]
Requested access to EMR logs with hope to see anything else, but also started to rework manifests to single `Scan` as it should be faster and finish ahead of other actions.

**Comment by alexanderdean** [comment]
Thanks @chuwy - please keep me posted on this as this is blocking release and causing serious disruption to Support Engineering.

**Comment by chuwy** [comment]
@alexanderdean I refactored manifests to use `scan` and reworked few suspicious, but minor calls. Will publish rc4 as soon as tests pass.

**Comment by alexanderdean** [comment]
Oh nice, thanks @chuwy !

**Comment by chuwy** [comment]
Two (or even three?) runs of affected pipeline went without issues so far. I think if until next morning there'll be no failures we can consider it fixed?

**Comment by alexanderdean** [comment]
Agree - fingers crossed...
