### ISSUE TITLE
Make SparkContext initialize eagerly

### ISSUE THREAD

**Issue by chuwy** [snowplow-archive/snowplow-snowflake-loader#24]
See #17 

After we refactored `getUnprocessed` to use DynamoDB it stopped to fail DynamoDB interaction and worked fine for 5 days, but failed two times on listing S3 bucket:

```
17/10/09 08:39:55 ERROR ApplicationMaster: User class threw exception: shadeaws.SdkClientException: Failed to sanitize XML document destined for handler class shadeaws.services.s3.model.transform.XmlRe[2/194]
SaxParser$ListObjectsV2Handler
shadeaws.SdkClientException: Failed to sanitize XML document destined for handler class shadeaws.services.s3.model.transform.XmlResponsesSaxParser$ListObjectsV2Handler
        at shadeaws.services.s3.model.transform.XmlResponsesSaxParser.sanitizeXmlDocument(XmlResponsesSaxParser.java:214)
        at shadeaws.services.s3.model.transform.XmlResponsesSaxParser.parseListObjectsV2Response(XmlResponsesSaxParser.java:315)
        at shadeaws.services.s3.model.transform.Unmarshallers$ListObjectsV2Unmarshaller.unmarshall(Unmarshallers.java:88)
        at shadeaws.services.s3.model.transform.Unmarshallers$ListObjectsV2Unmarshaller.unmarshall(Unmarshallers.java:77)
        at shadeaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:62)
        at shadeaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:31)
        at shadeaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:70)
        at shadeaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1503)
        at shadeaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1226)
        at shadeaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
        at shadeaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
        at shadeaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
        at shadeaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at shadeaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at shadeaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at shadeaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at shadeaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4187)
        at shadeaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4134)
        at shadeaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4128)
        at shadeaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:878)
        at com.snowplowanalytics.snowplow.analytics.scalasdk.RunManifests$.com$snowplowanalytics$snowplow$analytics$scalasdk$RunManifests$$isGlacierified(RunManifests.scala:136)
        at com.snowplowanalytics.snowplow.analytics.scalasdk.RunManifests$$anonfun$1.apply(RunManifests.scala:103)
        at com.snowplowanalytics.snowplow.analytics.scalasdk.RunManifests$$anonfun$1.apply(RunManifests.scala:103)
        at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:248)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
        at scala.collection.TraversableLike$class.filterNot(TraversableLike.scala:267)
        at scala.collection.AbstractTraversable.filterNot(Traversable.scala:104)
        at com.snowplowanalytics.snowplow.analytics.scalasdk.RunManifests$.listRunIds(RunManifests.scala:112)
        at com.snowplowanalytics.snowflake.core.ProcessManifest$.getUnprocessed(ProcessManifest.scala:37)
        at com.snowplowanalytics.snowflake.transformer.Main$.main(Main.scala:22)
        at com.snowplowanalytics.snowflake.transformer.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:637)
Caused by: shadeaws.AbortedException:
        at shadeaws.internal.SdkFilterInputStream.abortIfNeeded(SdkFilterInputStream.java:51)
        at shadeaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:71)
        at shadeaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.read1(BufferedReader.java:210)
        at java.io.BufferedReader.read(BufferedReader.java:286)
        at java.io.Reader.read(Reader.java:140)
        at shadeaws.services.s3.model.transform.XmlResponsesSaxParser.sanitizeXmlDocument(XmlResponsesSaxParser.java:186)
        ... 36 more
17/10/09 08:39:55 INFO ShutdownHookManager: Shutdown hook called
```

I believe this error has same root cause as in #17 - both errors have underlying `AbortedException`, which makes me believe some part of Spark calls `Thead.sleep`, while AWS SDK tries to silently "swallow" `InterruptedException` and turn them into `AbortedException`.

**Comment by chuwy** [comment]
Right now I found some evidences of incorrect `InterruptedException` handling in older AWS SDK versions. Despite `shadeaws` we're still using embedded into AMI, AWS SDK 1.10.75 (based on [source code](https://github.com/aws/aws-sdk-java/blob/355424771b951ef0066b19c3eab4b4356e270cf4/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/transform/XmlResponsesSaxParser.java#L214) in traceback).

I'm planning to publish assets compiled with bumped versions and prepared to latest AMI.

**Comment by alexanderdean** [comment]
This commit went into 0.3.0, updating milestone...

**Comment by chuwy** [comment]
Gotcha! YARN expects SparkContext to be initialized within 100 seconds. If it cannot retrieve it - ApplicationMaster fails to initialize. And state-fetching takes more than that for big archives. Working on fix.

**Comment by chuwy** [comment]
Renamed ticket to reflect code-change. Created separate one for previous implementation (#26).

**Comment by alexanderdean** [comment]
Glad to hear it's coming together!
